name: AnatEM

acquisition:
  source_url: "https://github.com/openbiocorpora/anatem/archive/refs/heads/master.zip"
  format: "zip"


loader:
  name: AnatEM_standoff
  params:
    paths:
      train: corpora/AnatEM/anatem-master/original-data/standoff/train
      dev: corpora/AnatEM/anatem-master/original-data/standoff/devel
      test: corpora/AnatEM/anatem-master/original-data/standoff/test
