name: BC5CDR

loader:
  name: bioc_xml
  params:
    paths:
      train: corpora/BC5CDR/CDR_TrainingSet.BioC.xml
      dev: corpora/BC5CDR/CDR_DevelopmentSet.BioC.xml
      test: corpora/BC5CDR/CDR_TestSet.BioC.xml
    label_infon_key: type
    id_infon_key: MESH
    id_format_list: [["|", "distributive", "False"]]
    qualifier_map: {}
    nil_labels: { -1 }
    doc_id_map:
        pmid: "__DOCUMENT_ID__"

