name: BioID

loader:
  name: bioc_xml
  params:
    paths:
      train: corpora/BioID/training.xml 
      dev: corpora/BioID/holdout.xml 
    label_infon_key: type
    id_format_list: [[",", "distributive", "False"]]

