name: NLM_Chem

loader:
  name: bioc_xml
  params:
    paths:
      train: corpora/NLM_Chem/BC7T2-NLMChem-corpus-train.BioC.xml
      dev: corpora/NLM_Chem/BC7T2-NLMChem-corpus-dev.BioC.xml
      test: corpora/NLM_Chem/BC7T2-NLMChem-corpus-test.BioC.xml
    label_infon_key: type
    id_format_list: [[",", "distributive", "False"]]
    nil_labels: { "-" }
    label_map: {"Chemical": "Chemical", "MeSH_Indexing_Chemical": null}
    doc_id_map:
        pmid: "article-id_pmid"



