logging:
    level: INFO

corpora:
    AnatEM: configs/AnatEM.yaml
    BC5CDR: configs/BC5CDR.yaml
    BioID: configs/BioID.yaml
    CHEMDNER: configs/CHEMDNER.yaml
    CRAFT: configs/CRAFT.yaml
    CellLink: configs/CellLink.yaml
    JNLPBA: configs/JNLPBA.yaml
    NCBI_Disease: configs/NCBI_Disease.yaml
    NLM_Chem: configs/NLM_Chem.yaml

bundles:
  AnatEM_train:
    - corpus_name: AnatEM
      subset_name: train
  AnatEM_test:
    - corpus_name: AnatEM
      subset_name: test
  BC5CDR_train:
    - corpus_name: BC5CDR
      subset_name: train
  BC5CDR_test:
    - corpus_name: BC5CDR
      subset_name: test
  BioID_train:
    - corpus_name: BioID
      subset_name: train
  BioID_dev:
    - corpus_name: BioID
      subset_name: dev
  CHEMDNER_train:
    - corpus_name: CHEMDNER
      subset_name: train
  CHEMDNER_test:
    - corpus_name: CHEMDNER
      subset_name: test
  CRAFT_train:
    - corpus_name: CRAFT
      subset_name: train
  CRAFT_test:
    - corpus_name: CRAFT
      subset_name: test
  CellLink_train:
    - corpus_name: CellLink
      subset_name: train
  CellLink_test:
    - corpus_name: CellLink
      subset_name: test
  JNLPBA_train:
    - corpus_name: JNLPBA
      subset_name: train
  JNLPBA_test:
    - corpus_name: JNLPBA
      subset_name: test
  NCBI_Disease_train:
    - corpus_name: NCBI_Disease
      subset_name: train
  NCBI_Disease_test:
    - corpus_name: NCBI_Disease
      subset_name: test
  NLM_Chem_train:
    - corpus_name: NLM_Chem
      subset_name: train
  NLM_Chem_test:
    - corpus_name: NLM_Chem
      subset_name: test
      
comparison_suites:
  AnatEM_TrainVsTest:
    - ["AnatEM_train", "AnatEM_test"]
  BC5CDR_TrainVsTest:
    - ["BC5CDR_train", "BC5CDR_test"]
  BioID_TrainVsTest:
    - ["BioID_train", "BioID_dev"]
  CHEMDNER_TrainVsTest:
    - ["CHEMDNER_train", "CHEMDNER_test"]
  CRAFT_TrainVsTest:
    - ["CRAFT_train", "CRAFT_test"]
  CellLink_TrainVsTest:
    - ["CellLink_train", "CellLink_test"]
  JNLPBA_TrainVsTest:
    - ["JNLPBA_train", "JNLPBA_test"]
  NCBI_Disease_TrainVsTest:
    - ["NCBI_Disease_train", "NCBI_Disease_test"]
  NLM_Chem_TrainVsTest:
    - ["NLM_Chem_train", "NLM_Chem_test"]
    
metrics:
  - result_name: AnatEM_token_overlap
    metric_name: token_overlap
    comparison_suite: AnatEM_TrainVsTest
  - result_name: BC5CDR_token_overlap
    metric_name: token_overlap
    comparison_suite: BC5CDR_TrainVsTest
  - result_name: BioID_token_overlap
    metric_name: token_overlap
    comparison_suite: BioID_TrainVsTest
  - result_name: CHEMDNER_token_overlap
    metric_name: token_overlap
    comparison_suite: CHEMDNER_TrainVsTest
  - result_name: CRAFT_token_overlap
    metric_name: token_overlap
    comparison_suite: CRAFT_TrainVsTest
  - result_name: CellLink_token_overlap
    metric_name: token_overlap
    comparison_suite: CellLink_TrainVsTest
  - result_name: JNLPBA_token_overlap
    metric_name: token_overlap
    comparison_suite: JNLPBA_TrainVsTest
  - result_name: NCBI_Disease_token_overlap
    metric_name: token_overlap
    comparison_suite: NCBI_Disease_TrainVsTest
  - result_name: NLM_Chem_token_overlap
    metric_name: token_overlap
    comparison_suite: NLM_Chem_TrainVsTest
  - result_name: AnatEM_mention_overlap
    metric_name: mention_overlap
    comparison_suite: AnatEM_TrainVsTest
  - result_name: BC5CDR_mention_overlap
    metric_name: mention_overlap
    comparison_suite: BC5CDR_TrainVsTest
  - result_name: BioID_mention_overlap
    metric_name: mention_overlap
    comparison_suite: BioID_TrainVsTest
  - result_name: CHEMDNER_mention_overlap
    metric_name: mention_overlap
    comparison_suite: CHEMDNER_TrainVsTest
  - result_name: CRAFT_mention_overlap
    metric_name: mention_overlap
    comparison_suite: CRAFT_TrainVsTest
  - result_name: CellLink_mention_overlap
    metric_name: mention_overlap
    comparison_suite: CellLink_TrainVsTest
  - result_name: JNLPBA_mention_overlap
    metric_name: mention_overlap
    comparison_suite: JNLPBA_TrainVsTest
  - result_name: NCBI_Disease_mention_overlap
    metric_name: mention_overlap
    comparison_suite: NCBI_Disease_TrainVsTest
  - result_name: NLM_Chem_mention_overlap
    metric_name: mention_overlap
    comparison_suite: NLM_Chem_TrainVsTest
  - result_name: AnatEM_mention_token_overlap
    metric_name: mention_token_overlap
    comparison_suite: AnatEM_TrainVsTest
  - result_name: BC5CDR_mention_token_overlap
    metric_name: mention_token_overlap
    comparison_suite: BC5CDR_TrainVsTest
  - result_name: BioID_mention_token_overlap
    metric_name: mention_token_overlap
    comparison_suite: BioID_TrainVsTest
  - result_name: CHEMDNER_mention_token_overlap
    metric_name: mention_token_overlap
    comparison_suite: CHEMDNER_TrainVsTest
  - result_name: CRAFT_mention_token_overlap
    metric_name: mention_token_overlap
    comparison_suite: CRAFT_TrainVsTest
  - result_name: CellLink_mention_token_overlap
    metric_name: mention_token_overlap
    comparison_suite: CellLink_TrainVsTest
  - result_name: JNLPBA_mention_token_overlap
    metric_name: mention_token_overlap
    comparison_suite: JNLPBA_TrainVsTest
  - result_name: NCBI_Disease_mention_token_overlap
    metric_name: mention_token_overlap
    comparison_suite: NCBI_Disease_TrainVsTest
  - result_name: NLM_Chem_mention_token_overlap
    metric_name: mention_token_overlap
    comparison_suite: NLM_Chem_TrainVsTest
  - result_name: AnatEM_identifier_overlap
    metric_name: identifier_overlap
    comparison_suite: AnatEM_TrainVsTest
  - result_name: BC5CDR_identifier_overlap
    metric_name: identifier_overlap
    comparison_suite: BC5CDR_TrainVsTest
  - result_name: BioID_identifier_overlap
    metric_name: identifier_overlap
    comparison_suite: BioID_TrainVsTest
  - result_name: CHEMDNER_identifier_overlap
    metric_name: identifier_overlap
    comparison_suite: CHEMDNER_TrainVsTest
  - result_name: CRAFT_identifier_overlap
    metric_name: identifier_overlap
    comparison_suite: CRAFT_TrainVsTest
  - result_name: CellLink_identifier_overlap
    metric_name: identifier_overlap
    comparison_suite: CellLink_TrainVsTest
  - result_name: JNLPBA_identifier_overlap
    metric_name: identifier_overlap
    comparison_suite: JNLPBA_TrainVsTest
  - result_name: NCBI_Disease_identifier_overlap
    metric_name: identifier_overlap
    comparison_suite: NCBI_Disease_TrainVsTest
  - result_name: NLM_Chem_identifier_overlap
    metric_name: identifier_overlap
    comparison_suite: NLM_Chem_TrainVsTest

output_path: "output/overlap_stats.json"
